Import('env', 'sys', 'integrEnv', 'plugins')

plugins += env.SharedLibrary('ao', ['direct/ao.cpp'])
plugins += env.SharedLibrary('direct', ['direct/direct.cpp'])
plugins += env.SharedLibrary('path', ['path/path.cpp'])
plugins += env.SharedLibrary('volpath', ['path/volpath.cpp'])
plugins += env.SharedLibrary('volpath_simple', ['path/volpath_simple.cpp'])
plugins += env.SharedLibrary('ptracer', ['ptracer/ptracer.cpp', 'ptracer/ptracer_proc.cpp'])

# Photon mapping-based techniques
plugins += env.SharedLibrary('photonmapper', ['photonmapper/photonmapper.cpp', 'photonmapper/bre.cpp'])
plugins += env.SharedLibrary('ppm', ['photonmapper/ppm.cpp'])
plugins += env.SharedLibrary('sppm', ['photonmapper/sppm.cpp'])

# Miscellaneous
plugins += env.SharedLibrary('vpl', ['vpl/vpl.cpp'])
plugins += env.SharedLibrary('adaptive', ['misc/adaptive.cpp'])
plugins += env.SharedLibrary('irrcache', ['misc/irrcache.cpp', 'misc/irrcache_proc.cpp'])
plugins += env.SharedLibrary('multichannel', ['misc/multichannel.cpp'])
plugins += env.SharedLibrary('field', ['misc/field.cpp'])

# Bidirectional techniques
bidirEnv = env.Clone()
bidirEnv.Append(LIBS=['mitsuba-bidir'])
bidirEnv.Append(LIBPATH=['#src/libbidir'])

plugins += bidirEnv.SharedLibrary('bdpt',
	['bdpt/bdpt.cpp', 'bdpt/bdpt_wr.cpp', 'bdpt/bdpt_proc.cpp'])

plugins += bidirEnv.SharedLibrary('pssmlt',
	['pssmlt/pssmlt.cpp', 'pssmlt/pssmlt_sampler.cpp',
    'pssmlt/pssmlt_proc.cpp']);

plugins += bidirEnv.SharedLibrary('mlt',
	['mlt/mlt.cpp', 'mlt/mlt_proc.cpp']
)

plugins += bidirEnv.SharedLibrary('erpt',
	['erpt/erpt.cpp', 'erpt/erpt_proc.cpp']
)

plugins += bidirEnv.SharedLibrary('cmlt',
	['cmlt/cmlt.cpp', 'cmlt/cmlt_sampler.cpp',
    'cmlt/cmlt_proc.cpp']);
    
plugins += bidirEnv.SharedLibrary('vcm',
	['vcm/vcm.cpp', 'vcm/vcm_proc.cpp'])
	
plugins += bidirEnv.SharedLibrary('upm',
	['upm/upm.cpp', 'upm/upm_proc.cpp'])
	
plugins += bidirEnv.SharedLibrary('epssmlt',
	['epssmlt/epssmlt.cpp', 'epssmlt/epssmlt_sampler.cpp',
    'epssmlt/epssmlt_proc.cpp']);

# we need OpenGl
visEnv = integrEnv.Clone()
if visEnv.has_key('GLLIB'):
	visEnv.Prepend(LIBS=visEnv['GLLIB'])
if visEnv.has_key('GLLIBDIR'):
	visEnv.Prepend(LIBPATH=visEnv['GLLIBDIR'])
if visEnv.has_key('GLFLAGS'):	
	visEnv.Prepend(CPPFLAGS=visEnv['GLFLAGS'])
	
plugins += visEnv.SharedLibrary('guided_path', ['guide/guided_path.cpp'])

visEnv.Append(LIBS=['mitsuba-bidir'])
visEnv.Append(LIBPATH=['#src/libbidir'])
plugins += visEnv.SharedLibrary('guided_bdpt',
	['guide/guided_bdpt.cpp', 'guide/guided_bdpt_wr.cpp', 'guide/guided_bdpt_proc.cpp'])
	
Export('plugins')






